// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCASxnoPq5-BSOnodQtSHRQ_PbBTNX2CQo',
    appId: '1:681238673880:web:72a58c8c02c9c6b1345aad',
    messagingSenderId: '681238673880',
    projectId: 'fir-notification-46641',
    authDomain: 'fir-notification-46641.firebaseapp.com',
    storageBucket: 'fir-notification-46641.firebasestorage.app',
    measurementId: 'G-ZW4RSK84J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWjMt5ZTLfjIgjs4pBbD4jzeYtX9RZde0',
    appId: '1:681238673880:android:3f0e3174895cf45b345aad',
    messagingSenderId: '681238673880',
    projectId: 'fir-notification-46641',
    storageBucket: 'fir-notification-46641.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIy3c0T0gos2r7Q8dB7lwuwckNnZyBlM8',
    appId: '1:681238673880:ios:56cfda8f3e9e0d2e345aad',
    messagingSenderId: '681238673880',
    projectId: 'fir-notification-46641',
    storageBucket: 'fir-notification-46641.firebasestorage.app',
    iosBundleId: 'com.yallaCoupon.yallaCoupon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIy3c0T0gos2r7Q8dB7lwuwckNnZyBlM8',
    appId: '1:681238673880:ios:56cfda8f3e9e0d2e345aad',
    messagingSenderId: '681238673880',
    projectId: 'fir-notification-46641',
    storageBucket: 'fir-notification-46641.firebasestorage.app',
    iosBundleId: 'com.yallaCoupon.yallaCoupon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCASxnoPq5-BSOnodQtSHRQ_PbBTNX2CQo',
    appId: '1:681238673880:web:6e1e2bf62c79e4f0345aad',
    messagingSenderId: '681238673880',
    projectId: 'fir-notification-46641',
    authDomain: 'fir-notification-46641.firebaseapp.com',
    storageBucket: 'fir-notification-46641.firebasestorage.app',
    measurementId: 'G-SCP9K42MTD',
  );
}
